// <auto-generated />
using System;
using Annuaire.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Annuaire.Migrations
{
    [DbContext(typeof(PersonneContext))]
    [Migration("20210831150616_Ram6")]
    partial class Ram6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Annuaire.Models.Info", b =>
                {
                    b.Property<string>("seed")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("seed");

                    b.Property<int>("page")
                        .HasColumnType("int")
                        .HasColumnName("page");

                    b.Property<int>("results")
                        .HasColumnType("int")
                        .HasColumnName("results");

                    b.Property<string>("version")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version");

                    b.HasKey("seed");

                    b.ToTable("Info");
                });

            modelBuilder.Entity("Annuaire.Models.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<int>("age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("first")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first");

                    b.Property<string>("last")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<int?>("rootIdRoot")
                        .HasColumnType("int");

                    b.Property<string>("service")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("rootIdRoot");

                    b.ToTable("Personne");
                });

            modelBuilder.Entity("Annuaire.Models.Result", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<int?>("RootIdRoot")
                        .HasColumnType("int");

                    b.Property<int?>("personneId")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.HasKey("email");

                    b.HasIndex("RootIdRoot");

                    b.HasIndex("personneId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("Annuaire.Models.Root", b =>
                {
                    b.Property<int>("IdRoot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRoot")
                        .UseIdentityColumn();

                    b.Property<string>("infoseed")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdRoot");

                    b.HasIndex("infoseed");

                    b.ToTable("Root");
                });

            modelBuilder.Entity("Annuaire.Models.Personne", b =>
                {
                    b.HasOne("Annuaire.Models.Root", "root")
                        .WithMany()
                        .HasForeignKey("rootIdRoot");

                    b.Navigation("root");
                });

            modelBuilder.Entity("Annuaire.Models.Result", b =>
                {
                    b.HasOne("Annuaire.Models.Root", null)
                        .WithMany("results")
                        .HasForeignKey("RootIdRoot");

                    b.HasOne("Annuaire.Models.Personne", "personne")
                        .WithMany()
                        .HasForeignKey("personneId");

                    b.Navigation("personne");
                });

            modelBuilder.Entity("Annuaire.Models.Root", b =>
                {
                    b.HasOne("Annuaire.Models.Info", "info")
                        .WithMany()
                        .HasForeignKey("infoseed");

                    b.Navigation("info");
                });

            modelBuilder.Entity("Annuaire.Models.Root", b =>
                {
                    b.Navigation("results");
                });
#pragma warning restore 612, 618
        }
    }
}
